### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.jjazzlab.JJazzLab#3]
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

https://raw.githubusercontent.com/jjazzboss/JJazzLab/bbd6ee18eeb55be3b002492cb70ba7487bfa427a/misc/org.jjazzlab.JJazzLab.desktop has no categories

**Comment by wvengen** [comment]
Implemented in https://github.com/jjazzboss/JJazzLab/issues/453.
Will be part of next release 4.1.1.
